### ISSUE TITLE
TODO: For BukkitPE

### ISSUE THREAD

**Issue by xZeroMCPE** [BukkitPE/BukkitPE#86]
- [ ] Bukkit API (Ability to load Spigot or Bukkit plugins on BukkitPE)
- [ ] More useful commands SpigotMC has!
- [ ] Better chunks loading
- [ ] Update to 16.0
- [ ] Fix / new / optimized API a little bit
- [ ] Fix high CPU usage

More will be added as some are marked as completed!
